version: '2.1'
orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/python:3.11.1
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      pip install --user tox

jobs:
  test_app:
    <<: *defaults
    working_directory: ~/project/decision_tree_api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox

  test_and_upload_decision_tree_model:
    <<: *defaults
    working_directory: ~/project/rental_bikes_decision_tree_model
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Fetch the data
          command: |
            tox -e fetch_data
      - run:
          name: Test the model
          command: |
            tox
      - run:
          name: Publish model to Gemfury
          command: |
            tox -e publish_model

  deploy_app_to_railway:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run: npm i -g @railway/cli
      - run:
          name: Deploy to Railway App (You must set RAILWAY_TOKEN env var)
          command: |
            cd decision_tree_api/ && railway up --detach --service=boss-fall

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - test_and_upload_decision_tree_model
      - deploy_app_to_railway:
          requires:
            - test_and_upload_decision_tree_model
          filters:
            branches:
              only:
                - main
                - demo